<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-Skates-b/blob/main/more_on_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 'more on numpy' assignments

There are five topics covered, plus a review section that has an assignment at the very beginnning. ✅
1. Vectors and Matrices ✅
2. Operations ✅
3. Vectorization and Performance ✅
4. Eiganvalues and Eiganvectors ✅
5. Quadratic Form: Diatomic Molecule Model


## Review

In [ ]:
import numpy as np
np.__version__


# explore NumPy
dir(np)[:20] # first 20 entries


# get help for a specific function
help(np.sin)


# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'
np.linspace?


Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

## Vectors and Matrices

### review of code and information

In [ ]:
# creating vectors
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

# creating matrices

A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

# Indexing and slicing

A[0, 1], A[:, 0], A[1]

# Random matrices

R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[ 1.31934744,  1.38635529,  0.7708435 ],
        [ 2.28620637, -1.24755046, -0.48134366],
        [-0.7015065 , -0.10689096,  0.06745751]]),
 array([[0.76983822, 0.81231429, 0.0577522 ],
        [0.6331098 , 0.62317269, 0.85703281],
        [0.61057138, 0.5653912 , 0.47106235]]))

### assignment

In [ ]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
    # A symmetric matrix A satisfies A = 0.5*(A + A.T);
    # An antisymmetric matrix satisfies A = 0.5*(A - A.T);
    # The `.T` attribute finds the transpose of the matrix.

import numpy as np
R = np.random.randn(5,5)
A = 0.5*(R + R.T)
B = 0.5*(R - R.T)
A, B

(array([[-1.21031065,  0.42285864,  0.47146485,  0.21012799, -0.89139182],
        [ 0.42285864, -1.38502433,  0.47882062, -0.21397618, -0.54987565],
        [ 0.47146485,  0.47882062,  0.14191482, -0.64958825,  0.02157938],
        [ 0.21012799, -0.21397618, -0.64958825, -0.74987404, -0.50615011],
        [-0.89139182, -0.54987565,  0.02157938, -0.50615011, -2.47625152]]),
 array([[ 0.        ,  1.97857909, -0.64983968, -0.78823747,  0.02181334],
        [-1.97857909,  0.        , -0.50014084, -0.47257994, -1.27838806],
        [ 0.64983968,  0.50014084,  0.        ,  0.20714296,  0.20328171],
        [ 0.78823747,  0.47257994, -0.20714296,  0.        ,  0.13060257],
        [-0.02181334,  1.27838806, -0.20328171, -0.13060257,  0.        ]]))

## Operations

### review

In [ ]:
# Elementwise multiplication (*)

A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

# Matrix multiplication (@)

A @ B

# Function equivalents for matrix multiplication

np.matmul(A, B), np.dot(A, B)


(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

### assignment

In [12]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences
import numpy as np
np.matmul?
np.dot?


The difference between `np.matmul`, `np.dot`, `@`, and `*`.

`np.matmul` is a matrix product of two arrays where scalars are not allowed.

`np.dot` is the dot product of two arrays where scalars are allowed. This function gets funky when matrices are in dimension 3 or higher.

`@` is matrix multiplication, and is equivilent to `np.dot` for basic cases, but is most useful for matrices in the dimension 3 or higher.

`*` instead multiples the components of matrices together, and not the matrix itself.

The `np.matmul`, `np.dot`, and `@` will yield the same result, while `*` yields a different result since it is a different operation.

In [ ]:
# 2. creating an example to showcase the difference.
  # create two random matrices
A = np.random.randn(3,3)
B = np.random.randn(3,3)

print(np.matmul(A, B))
print(np.dot(A, B))
print(A @ B)
print(A * B) #notice how this yields different results while the other three match


[[-2.18011403 -1.73708358  0.59000165]
 [-0.84184678  1.35212549 -0.09999037]
 [-0.74147145  0.64071636 -0.13539834]]
[[-2.18011403 -1.73708358  0.59000165]
 [-0.84184678  1.35212549 -0.09999037]
 [-0.74147145  0.64071636 -0.13539834]]
[[-2.18011403 -1.73708358  0.59000165]
 [-0.84184678  1.35212549 -0.09999037]
 [-0.74147145  0.64071636 -0.13539834]]
[[-0.06032097 -3.41439591  0.00780912]
 [ 1.13348481 -0.29641406 -0.05957322]
 [ 0.06795725  0.37417087 -0.09987786]]


## Vectorication and Performance

### Review

In [ ]:
# Loop version -- one element at a time

import math


%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

# Vectorized version

%%timeit
y_vec = np.sin(xs)

UsageError: Line magic function `%%timeit` not found.


### Assignment

In [ ]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`

"The %%timeit is a powerful [redacted link] used in Jupyter and Colab notebooks to measure the execution time of Python code snippets. It runs the code multiple times and provides statistical information like the best, worst, and average execution times, along with the standard deviation. This helps in comparing the performance of different implementations.

How it works:
When you put %%timeit at the beginning of a cell, it will execute all the code in that cell multiple times (usually in loops and runs) and then report the average, best, and worst execution times. It automatically determines the number of loops and runs to get a statistically sound measurement.

Usage:
%%timeit
x = [1, 2, 3]
sum(x)
This will output something like: 30.3 ns ± 0.945 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

It's very useful for optimizing code by allowing you to quickly compare the performance of different algorithms or approaches." - Gemini

In [ ]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator

Pseudocode:

We need to create a vectorized function for the total energy of a harmonic oscillator.

Equations: `E` `= K + U`
where `K` `= .5 mv^2` and `U` `= .5 kx^2`.

Define `total_E` as a function that yields `E`.

Next, to set up a vectorized function, we need to vectorize a time series... where `t` is a linspace, and `x` and `v` get defined in terms of time.

In [21]:
# actual code now for harmonic oscillator
import numpy as np
def total_E(x, v, m=.5, k=2):
  T = 0.5 * m * v**2
  U = 0.5 * k * x**2
  return T + U

t = np.linspace(0, 10, 100)
x = np.sin(t)
v = np.cos(t)
E = total_E(x, v)
print(E)

[0.25       0.25762629 0.28019497 0.3167881  0.3659173  0.42558431
 0.49336226 0.56649439 0.64200615 0.71682621 0.78791137 0.85237035
 0.90758136 0.9512988  0.9817445  0.99768014 0.99845755 0.98404512
 0.95502905 0.91258953 0.85845273 0.79482057 0.7242812  0.64970372
 0.57412145 0.50060859 0.43215517 0.37154544 0.3212446  0.28329857
 0.25925075 0.25007925 0.25615711 0.27723711 0.31246187 0.36039866
 0.41909773 0.48617157 0.55889206 0.63430139 0.7093324  0.78093331
 0.84619187 0.90245376 0.94743063 0.97929309 0.99674521 0.99907712
 0.98619399 0.95861982 0.91747615 0.86443643 0.80165799 0.73169424
 0.65739085 0.58177002 0.5079075  0.43880755 0.3772807  0.32582948
 0.28654659 0.2610298  0.25031696 0.25484382 0.27442624 0.30826773
 0.35499186 0.41269817 0.47903955 0.55131766 0.6265927  0.70180295
 0.77388935 0.8399199  0.89720889 0.94342618 0.97669195 0.99565315
 0.99953858 0.9881902  0.96206958 0.92223915 0.87031894 0.80842075
 0.73906218 0.6650643  0.58943686 0.5152559  0.44553862 0.3831

## Eignavalues and Eiganvectors

### review

In [ ]:
# example matrix
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

### assignment

In [ ]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?

The first array is our eigenvalues. The second array is our eigenvectors.

The code 'np.linalg.eigh(K)' automatically sorts the values from the least to the most.

The first eigenvalue, `9.99e-17`, corresponds to the first column of eigenvectors. The second value `1` to the second column. The third value `3` to the third column.

## Quadratic Form: Diatomic Molecule Model

### review

In [ ]:
# Constructing a stiffness/force-constant matrix

k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

# Diagonalize to find frequencies and normal mode displacement patterns

vals, vecs = np.linalg.eigh(K)
vals, vecs

# Vibrational frequencies (ignoring mass)

omega = np.sqrt(vals)
omega

array([ 0., 70.])

### assignment

In [ ]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
  # Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.


In [ ]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.


In [ ]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule
